version: '2'

services:
  webserver:
    build: .
    image: archon_web
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
      - db
    environment:
      - DB_HOST=172.17.0.1:3307
      - DB_NAME=archon_dev
      - DB_USER=archon
      - DB_PASS=archon

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=archon_dev
      - MYSQL_USER=archon
      - MYSQL_PASSWORD=archon
